### ISSUE TITLE
feat: Hydrate `Chat` and `User` ?

### ISSUE THREAD

**Issue by arkarwine** [grammyjs/hydrate#15]
Hydration for `Chat` and `User`.

**example** :

```typescript
// Hydration for `Chat`

await chat.sendMessage( "Hydration for chat is nice ! " )
await chat.approveChatJoinRequest( user_id )
await chat.setChatPermissions( ... )

// Hydration for `User`

await user.sendMessage( " This would be useful for captcha(s) ! " )
await user.approveChatJoinRequest( chat_id )
await user.restrictChatMember( ... )
```

**Comment by KnorpelSenf** [comment]
Would be great to have it, there just has not been any demand yet. I'd be happy to take contributions.

See https://github.com/grammyjs/hydrate/blob/03fa8fb0305543120191b746c25227fecc05ece0/src/plugin.ts#L135.

**Comment by arkarwine** [comment]
Hi, I've been trying to understand how things work. Struggling with it since I'm a beginner but I'll figure it out eventually.

The one main bit of code that I'm struggling to understanding is [this](https://github.com/grammyjs/hydrate/blob/03fa8fb0305543120191b746c25227fecc05ece0/src/plugin.ts#L84) part. Why was `next` returned instead of `await`ing it ?

How does it work and why ?

**Comment by KnorpelSenf** [comment]
You should read up on promises (check MDN) to understand this. The way how promises and async/await interact will tell you about this.

There is no difference. I could've used await. I probably should've used await in fact. I used return as a micro-optimisation. It makes stack traces and debugging worse, though. If I'd write the code today, I'd likely use await instead.

**Comment by KnorpelSenf** [comment]
Please don't hesitate to ask further questions, I'm happy to guide you through the process as much as necessary :)

**Comment by arkarwine** [comment]
> don't hesitate to ask further questions, I'm happy to guide you through the process as much as necessary :)
Thanks, It means a lot !

I figure ! 
The way async/await works in **Javascript** differs a lot from the way **Python**'s async/await works. ( I came from **Python** )
Unlike **Python**, In **Javascript** you can call a async function without `await` ing it.

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#description) calling a promise with `await` will _pauses the execution of its surrounding async function until the promise is settled (that is, fulfilled or rejected)_ . So that is certainly not what we want in the middleware since the function will continue without finish executing the `next()`, right ? 

But, [here](https://github.com/grammyjs/hydrate/blob/03fa8fb0305543120191b746c25227fecc05ece0/src/plugin.ts#L84) there is nothing left to execute after the `next()` so it works fine. 

Correct me if I'm wrong.

**Comment by arkarwine** [comment]
I'm working on the PR rn, this would be my first PR ( there were typo fix PRs but they don't count ), so there might be some flaws.

**Comment by arkarwine** [comment]
I'm stuck already.
I'm trying to hydrate `User` inside the `Message` ( `message.from` ) but how do I do that ?

Below is the user.ts file inside `data/` dir. In there I have `UserX`  but I can't figure out how to put the type in `message.from`.
```typescript
// user.ts

import { RawApi, User } from "../deps.deno.ts";
import { Other, Ret } from "../plugin.ts";

export interface UserXFragment {
    getUserProfilePhotos(
        other?: Other<"getUserProfilePhotos">,
        signal?: AbortSignal
    ): Ret<"getUserProfilePhotos">;
}

export type UserX = UserXFragment & User;

export function installUserMethods(api: RawApi, user: User) {
    const methods: UserXFragment = {
        getUserProfilePhotos: (other, signal) =>
            api.getUserProfilePhotos(
                {
                    user_id: user.id,
                    ...other,
                },
                signal
            ),
    };
    Object.assign(user, methods);
}

```

**Comment by KnorpelSenf** [comment]
Sorry for the silence, I did not forget you. Will get back to this soon!

**Comment by KnorpelSenf** [comment]
I'm back, sorry again for the delay.

> According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#description) calling a promise with `await` will _pauses the execution of its surrounding async function until the promise is settled (that is, fulfilled or rejected)_ . So calling `next()` without `await` is certainly not what we want in the middleware since the function will continue without finish executing the `next()`, right ?

Not quite. Basically, it's all about making sure you handle promises correctly. Calling `next` will just give you a promise. Now you need to make sure that the function itself only resolves after `next`'s promise resolves. This can be done in two ways:

1. By `await`ing the promise. This will make sure that the function execution pauses until `next` resolves, and only then it resolves itself.
2. By taking the promise from `next` and returning it to the caller. This will make sure that the function itself resolves exactly as soon as `next` resolves, since it returned its promise. That's what we did.

> But, [here](https://github.com/grammyjs/hydrate/blob/03fa8fb0305543120191b746c25227fecc05ece0/src/plugin.ts#L84) there is nothing left to execute after the `next()` so it works fine.

It's important to pass the promise from `next` to the caller. It would be incorrect to just call `next` without returning its value. That's why we `return next()`.

> I'm working on the PR rn, this would be my first PR ( there were typo fix PRs but they don't count ), so there might be some flaws.

Don't worry, everyone should post flawed code. If it's perfect by the time you push, you didn't push it early enough to receive valuable feedback :)



> I'm trying to hydrate `User` inside the `Message` ( `message.from` ) but how do I do that ?

By doing two things:

1. Doing lots of branching and assigning the properties to user objects wherever they can be found in updates. Ignore context aliases.
2. Adding the new types to the context object by intersecting it with an object that holds the added properties. For example, you can add it to `ctx.from` and `ctx.msg.from` by doing
  ```ts
  interface X {
    addedMethod(): void
  }
  interface Flavor {
    from?: X
    msg?: { from?: X }
  }
  type Result = Context & Flavor
  ```

Follow this pattern for all places where user objects could appear in the context object. This includes `ctx.message.from`.

You can see the two steps from this pattern be applied everywhere throughout this plugin.

> Below is the user.ts file inside `data/` dir. In there I have `UserX` but I can't figure out how to put the type in `message.from`.

Did that answer your question? :)

**Comment by KnorpelSenf** [comment]
@arkarwine are you still interested in attempting this?

**Comment by roziscoding** [comment]
> are you still interested in attempting this?

I wanna pick this up but the first thing I'm having a problem with is that `plugin.ts` imports `InputFileProxy` type but I can't seem to find it anywhere, nor does TypeScript

![image](https://github.com/grammyjs/hydrate/assets/3948961/544daa6b-1e11-47c8-8d07-54d89805d64d)

**Comment by KnorpelSenf** [comment]
This type existed on a previous major version of the types dependency. You need to refactor the plugin and get rid of this type.

**Comment by arkarwine** [comment]
Sorry for the delay. Internet and electricity keep getting cut out. I will pick this up again when my situation is good enough.

**Comment by KnorpelSenf** [comment]
Thanks for the update, please take your time. There's no rush.
